version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - ':'
    volumes:
      - ./data:/var/lib/postgresql/data      
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
